# Sample of the simplest configuration you can write
services:
  - name: service02
    strategy: LeastConnections
    matcher: "/"
    replicas:
      - url: "http://host.docker.internal:8082"
      - url: "http://host.docker.internal:8083"
      - url: "http://host.docker.internal:8084"
      - url: "http://host.docker.internal:8085"
      - url: "http://host.docker.internal:8086"
strategy: LeastConnections